name: hookee
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.0
  get_it: ^8.0.0
  injectable: ^2.0.0
  dio: ^5.0.0
  json_annotation: ^4.7.0
  dartz: ^0.10.0
  shared_preferences: ^2.0.0
  geolocator: ^10.0.0
  connectivity_plus: ^6.0.5
  cached_network_image: ^3.2.0
  equatable: ^2.0.5
  intl: ^0.19.0
  fade_scroll_app_bar: ^0.0.7
  flutter_chat_ui: ^1.6.15
  flutter_chat_types: ^3.4.5
  curved_navigation_bar: ^1.0.6
  provider: ^6.1.1
  smooth_page_indicator: ^1.0.0+2
  lottie: ^2.7.0
  google_fonts: ^5.0.0
  google_nav_bar: ^5.0.7
  country_code_picker: ^3.1.0
  flutter_staggered_grid_view: ^0.7.0 

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.0
  flutter_launcher_icons: ^0.13.1
  json_serializable: ^6.6.0
  hive_generator: ^2.0.0
  bloc_test: ^9.0.0
  mocktail: ^1.0.4
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
